version: '2'

services:
  phppgadmin:
    restart: always
    image: dockage/phppgadmin:latest
    container_name: matchmaking-phppgadmin
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
      - PHP_PG_ADMIN_SERVER_HOST=postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432

  postgres:
    image: "postgres:9.6.9"
    container_name: matchmaking-postgres
    environment:
      - POSTGRES_USER=andraz
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
